from brian2 import *
from utils.connections import (lamellar_conn, cross_lamellar_conn)
from params.general import igc_conn
from params.cells import (
    N_mgc_l,
    N_igc_l,
    N_bc_l,
    N_mc_l,
    N_pca3_l,
    N_ica3_l
) 

# Syntax: source_receptor_target
syn_params = {
    "pp_ampa_mgc": {
        "receptor" : "ampa_1",
        "p"        : 0.2,
        "g_max"    : 0.89 * nS,
        "tau_r"    : 0.1 * ms,
        "tau_d"    : 2.5 * ms,
        "delay"    : 3.0 * ms,
        "E"        : 0 * mV,
    },
    "pp_nmda_mgc": {
        "receptor" : "nmda_1",
        "p"        : 0.2,
        "g_max"    : 0.15 * nS,
        "tau_r"    : 0.33 * ms,
        "tau_d"    : 50.0 * ms,
        "delay"    : 3.0 * ms,
        "E"        : 0 * mV,
    },
    "pp_ampa_igc": {
        "receptor" : "ampa_1",
        "p"        : 0.2 * igc_conn,
        "g_max"    : 0.89 * nS,
        "tau_r"    : 0.1 * ms,
        "tau_d"    : 2.5 * ms,
        "delay"    : 3.0 * ms,
        "E"        : 0 * mV,
    },
    "pp_nmda_igc": {
        "receptor" : "nmda_1",
        "p"        : 0.2 * igc_conn,
        "g_max"    : 0.15 * nS,
        "tau_r"    : 0.33 * ms,
        "tau_d"    : 50.0 * ms,
        "delay"    : 3.0 * ms,
        "E"        : 0 * mV,
    },
    "pp_ampa_hipp": {
        "receptor" : "ampa_1",
        "p"        : 0.2,
        # "g_max"    : 12.0 * nS,
        "g_max"    : 1.2 * nS,
        "tau_r"    : 2.0 * ms,
        "tau_d"    : 11.0 * ms,
        "delay"    : 3.0 * ms,
        "E"        : 0 * mV,
    },
    "pp_nmda_hipp": {
        "receptor" : "nmda_1",
        "p"        : 0.2,
        "g_max"    : 3.04 * nS,
        "tau_r"    : 4.8 * ms,
        "tau_d"    : 110.0 * ms,
        "delay"    : 3.0 * ms,
        "E"        : 0 * mV,
    },
    # INNACURATE PARAMS
    "pp_ampa_pca3": {
        "receptor" : "ampa_1",
        "p"        : 0.2,
        "g_max"    : 0.75 * nS,
        "tau_r"    : 2.0 * ms,
        "tau_d"    : 6.3 * ms,
        "delay"    : 3.0 * ms,
        "E"        : 0 * mV,
    },
    # INNACURATE PARAMS
    "pp_nmda_pca3": {
        "receptor" : "nmda_1",
        "p"        : 0.2,
        "g_max"    : 0.13 * nS,
        "tau_r"    : 6.6 * ms,
        "tau_d"    : 126.0 * ms,
        "delay"    : 3.0 * ms,
        "E"        : 0 * mV,
    },

    "mgc_ampa_bc": {
        "receptor"  : "ampa_2",
        "condition" : lamellar_conn(N_mgc_l, N_bc_l),
        "g_max"     : 0.38 * nS,
        "tau_r"     : 2.5 * ms,
        "tau_d"     : 3.5 * ms,
        "delay"     : 0.8 * ms,
        "E"         : 0 * mV,
    },
    "mgc_nmda_bc": {
        "receptor"  : "nmda_2",
        "condition" : lamellar_conn(N_mgc_l, N_bc_l),
        "g_max"     : 0.02 * nS,
        "tau_r"     : 10.0 * ms,
        "tau_d"     : 130.0 * ms,
        "delay"     : 0.8 * ms,
        "E"         : 0 * mV,
    },
    "mgc_ampa_mc": {
        "receptor"  : "ampa_1",
        "condition" : lamellar_conn(N_mgc_l, N_mc_l),
        "g_max"     : 6.84 * nS,
        "tau_r"     : 0.5 * ms,
        "tau_d"     : 6.2 * ms,
        "delay"     : 1.5 * ms,
        "E"         : 0 * mV,
    },
    "mgc_nmda_mc": {
        "receptor"  : "nmda_1",
        "condition" : lamellar_conn(N_mgc_l, N_mc_l),
        "g_max"     : 1.22 * nS,
        "tau_r"     : 4.0 * ms,
        "tau_d"     : 100.0 * ms,
        "delay"     : 1.5 * ms,
        "E"         : 0 * mV,
    },
    # INNACURATE PARAMS
    "mgc_ampa_pca3": {
        "receptor" : "ampa_2",
        "condition" : lamellar_conn(N_mgc_l, N_pca3_l),
        "g_max"    : 1 * nS,
        "tau_r"    : 6.6 * ms,
        "tau_d"    : 126.0 * ms,
        "delay"    : 3.0 * ms,
        "E"        : 0 * mV,
    },
    # INNACURATE PARAMS
    "mgc_nmda_pca3": {
        "receptor" : "nmda_2",
        "condition" : lamellar_conn(N_mgc_l, N_pca3_l),
        "g_max"    : 1 * nS,
        "tau_r"    : 6.6 * ms,
        "tau_d"    : 126.0 * ms,
        "delay"    : 3.0 * ms,
        "E"        : 0 * mV,
    },
    # INNACURATE PARAMS
    "mgc_ampa_ica3": {
        "receptor" : "ampa_1",
        "condition" : lamellar_conn(N_mgc_l, N_ica3_l),
        "g_max"    : 1 * nS,
        "tau_r"    : 6.6 * ms,
        "tau_d"    : 126.0 * ms,
        "delay"    : 3.0 * ms,
        "E"        : 0 * mV,
    },
    # INNACURATE PARAMS
    "mgc_nmda_ica3": {
        "receptor" : "nmda_1",
        "condition" : lamellar_conn(N_mgc_l, N_ica3_l),
        "g_max"    : 1 * nS,
        "tau_r"    : 6.6 * ms,
        "tau_d"    : 126.0 * ms,
        "delay"    : 3.0 * ms,
        "E"        : 0 * mV,
    },

    "igc_ampa_bc": {
        "receptor"  : "ampa_3",
        "condition" : lamellar_conn(N_igc_l, N_bc_l),
        "g_max"     : 0.38 * nS,
        "tau_r"     : 2.5 * ms,
        "tau_d"     : 3.5 * ms,
        "delay"     : 0.8 * ms,
        "E"         : 0 * mV,
    },
    "igc_nmda_bc": {
        "receptor"  : "nmda_3",
        "condition" : lamellar_conn(N_igc_l, N_bc_l),
        "g_max"     : 0.02 * nS,
        "tau_r"     : 10.0 * ms,
        "tau_d"     : 130.0 * ms,
        "delay"     : 0.8 * ms,
        "E"         : 0 * mV,
    },
    "igc_ampa_mc": {
        "receptor"  : "ampa_2",
        "condition" : lamellar_conn(N_igc_l, N_mc_l),
        "g_max"     : 6.84 * nS,
        "tau_r"     : 0.5 * ms,
        "tau_d"     : 6.2 * ms,
        "delay"     : 1.5 * ms,
        "E"         : 0 * mV,
    },
    "igc_nmda_mc": {
        "receptor"  : "nmda_2",
        "condition" : lamellar_conn(N_igc_l, N_mc_l),
        "g_max"     : 1.22 * nS,
        "tau_r"     : 4.0 * ms,
        "tau_d"     : 100.0 * ms,
        "delay"     : 1.5 * ms,
        "E"         : 0 * mV,
    },
    # INNACURATE PARAMS
    "igc_ampa_pca3": {
        "receptor" : "ampa_3",
        "condition" : lamellar_conn(N_igc_l, N_pca3_l),
        "g_max"    : 1 * nS,
        "tau_r"    : 6.6 * ms,
        "tau_d"    : 126.0 * ms,
        "delay"    : 3.0 * ms,
        "E"        : 0 * mV,
    },
    # INNACURATE PARAMS
    "igc_nmda_pca3": {
        "receptor" : "nmda_3",
        "condition" : lamellar_conn(N_igc_l, N_pca3_l),
        "g_max"    : 1 * nS,
        "tau_r"    : 6.6 * ms,
        "tau_d"    : 126.0 * ms,
        "delay"    : 3.0 * ms,
        "E"        : 0 * mV,
    },
    # INNACURATE PARAMS
    "igc_ampa_ica3": {
        "receptor" : "ampa_2",
        "condition" : lamellar_conn(N_igc_l, N_ica3_l),
        "g_max"    : 1 * nS,
        "tau_r"    : 6.6 * ms,
        "tau_d"    : 126.0 * ms,
        "delay"    : 3.0 * ms,
        "E"        : 0 * mV,
    },
    # INNACURATE PARAMS
    "igc_nmda_ica3": {
        "receptor" : "nmda_2",
        "condition" : lamellar_conn(N_igc_l, N_ica3_l),
        "g_max"    : 1 * nS,
        "tau_r"    : 6.6 * ms,
        "tau_d"    : 126.0 * ms,
        "delay"    : 3.0 * ms,
        "E"        : 0 * mV,
    },

    "bc_gaba_mgc": {
        "receptor"  : "gaba_1",
        "condition" : lamellar_conn(N_bc_l, N_mgc_l),
        "g_max"     : 25.0 * nS,
        "tau_r"     : 0.9 * ms,
        "tau_d"     : 6.8 * ms,
        "delay"     : 0.85 * ms,
        "E"         : -86.0 * mV,
    },
    "bc_gaba_mc": {
        "receptor"  : "gaba_1",
        "condition" : lamellar_conn(N_bc_l, N_mc_l),
        "g_max"     : 3.08 * nS,
        "tau_r"     : 0.3 * ms,
        "tau_d"     : 3.3 * ms,
        "delay"     : 1.5 * ms,
        "E"         : -86.0 * mV,
    },

    "mc_ampa_mgc": {
        "receptor"  : "ampa_2",
        "condition" : cross_lamellar_conn(N_mc_l, N_mgc_l),
        "p"         : 0.2,
        "g_max"     : 0.05 * nS,
        "tau_r"     : 0.1 * ms,
        "tau_d"     : 2.5 * ms,
        "delay"     : 3.0 * ms,
        "E"         : 0 * mV,
    },
    "mc_nmda_mgc": {
        "receptor"  : "nmda_2",
        "condition" : cross_lamellar_conn(N_mc_l, N_mgc_l),
        "p"         : 0.2,
        "g_max"     : 0.01 * nS,
        "tau_r"     : 0.33 * ms,
        "tau_d"     : 50.0 * ms,
        "delay"     : 3.0 * ms,
        "E"         : 0 * mV,
    },
    "mc_ampa_igc": {
        "receptor"  : "ampa_2",
        "condition" : cross_lamellar_conn(N_mc_l, N_igc_l),
        "p"         : 0.2 * igc_conn,
        "g_max"     : 0.05 * nS,
        "tau_r"     : 0.1 * ms,
        "tau_d"     : 2.5 * ms,
        "delay"     : 3.0 * ms,
        "E"         : 0 * mV,
    },
    "mc_nmda_igc": {
        "receptor"  : "nmda_2",
        "condition" : cross_lamellar_conn(N_mc_l, N_igc_l),
        "p"         : 0.2 * igc_conn,
        "g_max"     : 0.01 * nS,
        "tau_r"     : 0.33 * ms,
        "tau_d"     : 50.0 * ms,
        "delay"     : 3.0 * ms,
        "E"         : 0 * mV,
    },
    "mc_ampa_bc": {
        "receptor"  : "ampa_4",
        "condition" : cross_lamellar_conn(N_mc_l, N_bc_l),
        "p"         : 0.2,
        "g_max"     : 3.23 * nS,
        "tau_r"     : 2.5 * ms,
        "tau_d"     : 3.5 * ms,
        "delay"     : 3.0 * ms,
        "E"         : 0 * mV,
    },
    "mc_nmda_bc": {
        "receptor"  : "nmda_4",
        "condition" : cross_lamellar_conn(N_mc_l, N_bc_l),
        "p"         : 0.2,
        "g_max"     : 0.19 * nS,
        "tau_r"     : 10.0 * ms,
        "tau_d"     : 130.0 * ms,
        "delay"     : 3.0 * ms,
        "E"         : 0 * mV,
    },

    "hipp_gaba_mgc": {
        "receptor" : "gaba_2",
        "p"        : 0.2,
        "g_max"    : 0.12 * nS,
        "tau_r"    : 0.9 * ms,
        "tau_d"    : 6.8 * ms,
        "delay"    : 1.6 * ms,
        "E"        : -86.0 * mV,
    },

    # INNACURATE PARAMS
    "pca3_ampa_pca3": {
        "receptor" : "ampa_4",
        # "p"        : 0.01,
        "p"        : 0.05,
        "g_max"    : 2 * nS,
        "tau_r"    : 6.6 * ms,
        "tau_d"    : 126.0 * ms,
        "delay"    : 3.0 * ms,
        "E"        : 0 * mV,
    },
    # INNACURATE PARAMS
    "pca3_nmda_pca3": {
        "receptor" : "nmda_4",
        "p"        : 0.01,
        "g_max"    : 2 * nS,
        "tau_r"    : 6.6 * ms,
        "tau_d"    : 126.0 * ms,
        "delay"    : 3.0 * ms,
        "E"        : 0 * mV,
    },
    # INNACURATE PARAMS
    "pca3_ampa_ica3": {
        "receptor" : "ampa_3",
        "condition" : lamellar_conn(N_pca3_l, N_ica3_l),
        "g_max"    : 1 * nS,
        "tau_r"    : 6.6 * ms,
        "tau_d"    : 126.0 * ms,
        "delay"    : 3.0 * ms,
        "E"        : 0 * mV,
    },
    # INNACURATE PARAMS
    "pca3_nmda_ica3": {
        "receptor" : "nmda_3",
        "condition" : lamellar_conn(N_pca3_l, N_ica3_l),
        "g_max"    : 1 * nS,
        "tau_r"    : 6.6 * ms,
        "tau_d"    : 126.0 * ms,
        "delay"    : 3.0 * ms,
        "E"        : 0 * mV,
    },
    # INNACURATE PARAMS
    "pca3_ampa_mc": {
        "receptor" : "ampa_3",
        "condition" : lamellar_conn(N_pca3_l, N_mc_l),
        "g_max"    : 1 * nS,
        "tau_r"    : 6.6 * ms,
        "tau_d"    : 126.0 * ms,
        "delay"    : 3.0 * ms,
        "E"        : 0 * mV,
    },
    # INNACURATE PARAMS
    "pca3_nmda_mc": {
        "receptor" : "nmda_3",
        "condition" : lamellar_conn(N_pca3_l, N_mc_l),
        "g_max"    : 1 * nS,
        "tau_r"    : 6.6 * ms,
        "tau_d"    : 126.0 * ms,
        "delay"    : 3.0 * ms,
        "E"        : 0 * mV,
    },

    # INNACURATE PARAMS
    "ica3_gaba_pca3": {
        "receptor" : "gaba_1",
        "condition" : lamellar_conn(N_ica3_l, N_pca3_l),
        "g_max"    : 30.0 * nS,
        "tau_r"    : 0.5 * ms,
        "tau_d"    : 6.0 * ms,
        "delay"    : 1.6 * ms,
        "E"        : -86.0 * mV,
    },
}